name: Slack Notification
on:
  pull_request:
    types: [ closed ]

jobs:
  slack-notify:
    name: Notify Devs
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        name: Slack Notification
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              username: 'Rebase Notifier',
              attachments: [{
                color: 'good',
                text: '${{ github.actor }} merged `${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}` into `${{ github.event.pull_request.base.ref }}` from `${{ github.event.pull_request.head.ref }}`'
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}